trigger:
- main

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            pip install build
            pip install twine
            pip install twine keyring artifacts-keyring
          displayName: 'Install build and twine'

        - script: |
            python -m build -w
          displayName: 'Python build'

        - task: TwineAuthenticate@1
          inputs:
            artifactFeed: 'integration-connectors'
        - script: |
            python -m twine upload -r integration-connectors --config-file $(PYPIRC_PATH) dist/*.whl
          displayName: 'Upload to feed'