[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/integration_interfaces"]

[project]
name = "integration_interfaces"
version = "0.0.30"
authors = [
  { name="Elizabeth Hunt", email="ehunt@seattleu.edu" },
]
description = "Interface Connectors for Integrations"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas",
  "pysmb",
  "paramiko",
  "pyodbc",
  "tenacity",
  "boto3",
    "Office365-REST-Python-Client==2.5.4"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://dev.azure.com/seattleu-its/_git/Standard_Integration_Connectors"
